# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 55f6c3884618cf08b5c8a0bf696d95e6a9b77aeec542d74b223b3ea5e42b073a33df54909b254692c0daff1598aff36b452be853d791201768d983fa889da52b

test:
  secret_key_base: 29c32fd5606faadf5d5b90d73ac06058cfc870918096e50f0ed0f47405261b362b09085ec98e38a07bc902247b3954fb93e6acec9fca3cde50cbf1063c18b115

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
